### ISSUE TITLE
正式启动前的零碎信息收集处

### ISSUE THREAD

**Issue by tsingyu42** [MYF2000/matlab-final-homework#1]
## 此帖闭环设定

此帖输入：各种原始、零碎的想法及后续讨论。
此帖输出：项目的 README 文件，内容包括项目的闭环设定、各子项目的具体内容和完成方式，以及处理信息和操作文件的规范等。

**Comment by tsingyu42** [comment]
我这几天好好琢磨下如何用它协作。之前一直都在拿它自娱自乐，也不熟具体操作。

除了上述的官方入门教程，还有这些可作为充分的延伸参考：

* https://www.yangzhiping.com/tech/github.html
* https://github.com/OpenMindClub/Share/wiki/HbGitHub
* lab.github.com

有啥疑问或想法的话直接po出来就行了 [嘿哈] 这样进展会快一些，而且互相提问可以帮助我们自己降低认知负荷

我周末大致琢磨完上面的东西之后，就一步步分解、展开我们要做的事情，然后我们就可以开始了 [拳头]

**Comment by tsingyu42** [comment]
git 代码不需要学 我们懂得在网页和本地客户端中点各种按钮操作就行了

**Comment by tsingyu42** [comment]
报告也用 GitHub 就行了 这个不用再引入新平台了 细节周末补充 这个好解决

**Comment by tsingyu42** [comment]
> 老师说分析代码optional，then....[旺柴]你们想用什么做数据分析吖？」
> - - - - - - - - - - - - - - -
> 老师说数据分析可以不用matlab。spss/R/python/....都可 

到时看分工吧 分析的话如果是我来做我挺想用 Python 练练手的

**Comment by tsingyu42** [comment]
麦云飞 5-7 20:37
 总共要做的事情大概有 文献理解 + 实验程序 + 收取数据 + 统计分析 + 写报告
 
 麦云飞 5-7 20:37
 这里周末会仔细整理整理

麦云飞 5-7 20:38
 文献和收数据是大家一起做的 剩余的到时再分工
 
 麦云飞 5-7 20:38
 大致会用 GitHub 后就可以先开始看看论文了

分工的话我继续细化想法：文献理解和找被试是大家一起，然后剩下刚好三个部分，或许可以一个人领一个，然后剩下两个人对那个人的工作进行校验和push意见。

↑先放到这里，周末全部整理起来。

**Comment by tsingyu42** [comment]
对于实验设计代码和报告本身以外的内容，我们到时候直接附上 GitHub 仓库的链接就行了。所有东西都可以让老师看到。

**Comment by tsingyu42** [comment]
互相称呼或在ChangeLog（后续会提到这个）里自称的时候用任意昵称即可，可以保护自己真实信息。像我自己已经处于公开状态就无所谓了。

**Comment by tsingyu42** [comment]
这里发出的内容是可以 edit 的，但是仍然需要注意一些措辞（特别是涉及到身份信息时），因为可以看历史版本。不然的话只能删除帖子或楼层。

**Comment by tsingyu42** [comment]
## 项目展开与分工

* **组块一：理解文献**（全员）
  * 【待展开】
* **组块二：设计程序**
  * 代码编写（MYF）
  * 审阅与运行代码（GYL HY）
* **组块三：收集数据**（全员）
  * 【待展开】
* **组块四：统计分析**
  * 整理数据【待定 视具体情况灵活解决】
  * 统计分析（GYL）
  * 输出统计结果（GYL）
  * 审阅分析过程及结果（HY MYF）
* **组块五：撰写报告**
  * 撰写报告（HY）
  * 审阅报告（GYL MYF）

## 各组块闭环设定

待展开

**Comment by tsingyu42** [comment]
为保护隐私，在正式结课、出成绩后此仓库封闭。（设为 Private ，届时会设置成员以能够继续访问。）

**Comment by ghost** [comment]
**零碎想法**

1. participants

> Participants. We recruited 132 participants, N = 88 healthy controls (50 female;
age = 23 ± 5 yr) and N = **44 people with unmedicated mood and anxiety symptoms**
(28 female; age = 28 ± 9 yr), from the local community (that is not through clinical
services, but rather through advertisements on noticeboards and internet sites; this
was to increase the probability of recruiting unmedicated participants).The two
groups were recruited through separate advertising campaigns. The symptomatic
group **responded to an advert** asking for people for whom anxiety/depression
was impacting their lives and then **underwent a standardized clinical screen**.

我们可以找到多少_people with unmedicated mood and anxiety symptoms_？怎么确定他们是 _people with unmedicated mood and anxiety symptoms_？量表/clinical screen/....etc ？？ 这些方法的可操作性和可靠性？

**Comment by MYF2000** [comment]
> **零碎想法**
> 
> 1. participants
> 
> > Participants. We recruited 132 participants, N = 88 healthy controls (50 female;
> > age = 23 ± 5 yr) and N = **44 people with unmedicated mood and anxiety symptoms**
> > (28 female; age = 28 ± 9 yr), from the local community (that is not through clinical
> > services, but rather through advertisements on noticeboards and internet sites; this
> > was to increase the probability of recruiting unmedicated participants).The two
> > groups were recruited through separate advertising campaigns. The symptomatic
> > group **responded to an advert** asking for people for whom anxiety/depression
> > was impacting their lives and then **underwent a standardized clinical screen**.
> 
> 我们可以找到多少_people with unmedicated mood and anxiety symptoms_？怎么确定他们是 _people with unmedicated mood and anxiety symptoms_？量表/clinical screen/....etc ？？ 这些方法的可操作性和可靠性？

了解，当项目推进至组块三时再开始考虑。总之这应该不会是个太重要的问题，因为本课程中实验程序设计相对是个重心。

如果不容易找到可判定为具有焦虑障碍的被试，则这个变量干脆就用性别来代替好了。

**Comment by tsingyu42** [comment]
> 怎么确定他们是 people with unmedicated mood and anxiety symptoms？量表/clinical screen/....etc ？？ 

@Cl-06 

在文章的“方法”部分（PDF 文档的第 6 页）找到了，是状态-特质焦虑量表 (State-Trait Anxiety Inventory, STAI) 和贝克抑郁量表 (Beck Depression Inventory, BDI) 。诊断为一般焦虑障碍***或***重性抑郁障碍并满足一些被试筛选原则的人即可作为控制组的被试。这些我都在整理成方便消化的文字，整理完后会放到此仓库里。

---

勘误。具体诊断方式不清楚。是由一批受过精神病理专家专业训练的人使用 Mini International Neuropsychiatric Interview 系统做出诊断。两个量表只是后续用于 continuous measurement ，但是文章似乎没详细说明具体作用。

**Comment by tsingyu42** [comment]
## 期末作业（考试）说明事项

1. 从20篇文章中选择一篇，每篇文章被选的次数不能超过两次。每个组确定选定文章后，到学习委员那登记；
2. 作业的具体要求是用PTB-3将文章里的任务编出来，采集一些人的数据，做相应的分析，形成一个研究报告。最后提交的材料包括实验程序代码，分析代码（optional），以及研究报告。
3. 程序代码需要有明确的注释。另外，我们会联系作者或者在网上下载这些文章里用到的原始程序代码，如果后面提交的代码与原始代码有5行以上的重叠，或者总体架构非常相似，视为作弊。
4. 期末作业这部分每位同学的分数包含两部分：小组得分+贡献分。小组得分根据每个小组的作业质量来定，所有成员的分数是一样的。贡献分总额=3*小组成员人数，分配到某个小组成员的分数取决于该成员的贡献。贡献大小由小组成员投票决定（每人可以投一个人，不可以投自己）。
5. 不一定要完全重复文献里的实验设计，在参考文献的基础上有自己的创新更好。
6. 作业评分的比重主要在程序代码和结果展示。前言和讨论可以参考原始的文章。但肯定不能全文翻译，可以加点自己的理解。另外，讨论的时候，可以说下和之前文章在结果上的异同。任何一个部分有自己的创新点都是加分项。
7. 作业提交的时间和你们闭卷考试的时间一致。也即在你们考试周结束前提交作业即可。
8. 如果有其他需要注意的事项，后面会再补充。

**Comment by tsingyu42** [comment]
协作方式：

其它账号写出文档或代码后，向 MYF2000 的仓库发出 Pull Request ，此时大家可点进 PR 处审阅代码做出评论。
