### ISSUE TITLE
Markdown语法快速入门

### ISSUE THREAD

**Issue by tsingyu42** [MYF2000/matlab-final-homework#2]
## Markdown语法快速入门

具体是什么可百度。它是个高效排版的语法，你可以在任何文本编辑器上打这些内容，然后在特定支持渲染的地方，比如GitHub，亦或是本地渲染器，渲染出排版效果。

**Comment by tsingyu42** [comment]
```
# 一级标题

## 二级标题

### 三级标题

#### 四级标题

##### 五级标题

###### 最多到六级标题
```

# 一级标题

## 二级标题

### 三级标题

#### 四级标题

##### 五级标题

###### 最多到六级标题

**Comment by tsingyu42** [comment]
```
*斜体*

**加粗**

***斜体+加粗***
```

*斜体*

**加粗**

***斜体+加粗***

**Comment by tsingyu42** [comment]
文段使用两个空格跳行，但是更推荐多空一行来换行，这样比较简单。

**Comment by tsingyu42** [comment]
```
[这是一个超链接](baidu.com)
```
[这是一个超链接](baidu.com)

**Comment by tsingyu42** [comment]
```
![图片的名字 是什么不重要](http://img5.imgtn.bdimg.com/it/u=3339362317,2522722352&fm=11&gp=0.jpg)
```
![图片的名字 是什么不重要](http://img5.imgtn.bdimg.com/it/u=3339362317,2522722352&fm=11&gp=0.jpg)

这里的机制是图片上传至GitHub服务器，再显示出来，额看来现在这部分网址被ban了。

可能上传到 [sm.ms](https://sm.ms/) 图床的图片就可以正常显示。

**Comment by tsingyu42** [comment]
```
> 这是引用balabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabala
>> 叠一层
> 引用
>>>>> 引用
```
> 这是引用balabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabalabala
>> 叠一层
> 引用
>>>>> 引用

**Comment by tsingyu42** [comment]
```
分割线↓

---

分割线↑
```

分割线↓

---

分割线↑

**Comment by tsingyu42** [comment]
一段文字的上一行和下下一行使用三个“`”，这段文字会变成代码块，就是上面灰灰的，不会有渲染效果的文字

    除了三个“`”，使用缩进（TAB或四个空格）也可以，这是单行的代码块。

**Comment by tsingyu42** [comment]
```
- 子弹清单
- 子弹清单
- 子弹清单
- 子弹清单

* 子弹清单
* 子弹清单
* 子弹清单
* 子弹清单
```

- 子弹清单
- 子弹清单
- 子弹清单
- 子弹清单

* 子弹清单
* 子弹清单
* 子弹清单
* 子弹清单

（或者叫做无序列表）

**Comment by tsingyu42** [comment]
```
1. 有序清单
1. 有序清单
1. 有序清单
2. 有序清单
3. 有序清单
```
1. 有序清单
1. 有序清单
1. 有序清单
2. 有序清单
3. 有序清单

**Comment by tsingyu42** [comment]
刚开始上手会需要那么一小阵时间，上手后就发现很难离开这个语言了，因为真的很简洁方便。本地文件使用.md格式，任意文本编辑器都可以（Windows 推荐 Atom，万能的集成开发环境，同时搞定 Python 和 R 等等种种语言的开发），渲染器则百度。

**Comment by tsingyu42** [comment]
一段文字之后两个空格跳到下一行。

不过默认回车两下空一行（就像这一段一样），美观。

**Comment by MaiYunfei2000** [comment]
互相称呼或在ChangeLog（后续会提到这个）里自称的时候用任意昵称即可，可以保护自己真实信息。像我自己已经处于公开状态就无所谓了。

**Comment by tsingyu42** [comment]
这些渲染效果是可以复制进 Word 等文档工具里的。不过对于 Word 嘛，有时比较无力吐槽。

**Comment by ghost** [comment]
> ```
> # 一级标题
> 
> ## 二级标题
> 
> ### 三级标题
> 
> #### 四级标题
> 
> ##### 五级标题
> 
> ###### 最多到六级标题
> ```
> 
> # 一级标题
> ## 二级标题
> ### 三级标题
> #### 四级标题
> ##### 五级标题
> ###### 最多到六级标题

可以尝试使用快捷键，也许更快噢
标题快捷键：`ctrl+1/2/3/4/5/6`

**Comment by tsingyu42** [comment]
> 可以尝试使用快捷键，也许更快噢

谢谢分享，以后有机会用 Windows 的时候试试。Mac 上无论是这里还是本地编辑器都没有快捷键，无论是 Ctrl 还是 CMD。
